# moirai 2.0 R small finetune config
_target_: uni2ts.model.moirai2.Moirai2Finetune
module:
  _target_: uni2ts.model.moirai2.Moirai2Module.from_pretrained
  pretrained_model_name_or_path: Salesforce/moirai-2.0-R-small
module_kwargs:
  d_model: 384
  num_layers: 6
  patch_sizes: [8, 16, 32, 64, 128]  # or fixed?
  max_seq_len: 512
  attn_dropout_p: 0.0
  dropout_p: 0.0
  scaling: true
min_patches: 2
min_mask_ratio: 0.15
max_mask_ratio: 0.5
max_dim: 128
loss_func:
  _target_: uni2ts.loss.packed.PackedMSELoss  # assume for 2.0
val_metric:
  - _target_: uni2ts.loss.packed.PackedMSELoss
  - _target_: uni2ts.loss.packed.PackedNRMSELoss
    normalize: absolute_target_squared
lr: 5e-7
weight_decay: 1e-1
beta1: 0.9
beta2: 0.98
num_training_steps: null
num_warmup_steps: 0
patch_size: 64  # for 5m data
context_length: 500
prediction_length: 12
target_dim: 1
feat_dynamic_real_dim: 1
past_feat_dynamic_real_dim: 5
finetune_pattern: full